### ISSUE TITLE
Fails on OsX

### ISSUE THREAD

**Issue by Fabijancic** [uktrade/mobius3#41]
mobius3 fails to run on OsX because od wrong imports:
```
Traceback (most recent call last):
  File "/Users/username/developer_tools/file-ingestion/main.py", line 3, in <module>
    from mobius3 import Syncer
  File "/Users/username/developer_tools/file-ingestion/.venv/lib/python3.9/site-packages/mobius3.py", line 56, in <module>
    libc = ctypes.CDLL('libc.so.6', use_errno=True)
  File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libc.so.6, 6): image not found
```

This should probably just be changed so it imports `.dylib` instead of `.so` if the platform is darwin.
e.g. https://stackoverflow.com/a/35675786

**Comment by michalc** [comment]
Hi,

Thanks for the report. However, I suspect is't not just a naming thing: mobius3 uses the linux-specific inotify API that isn't present on MacOS. While not impossible that down the line using an API that _is_ present on MacOS could be added, it's not a current plan.
